# Generated by Django 2.2 on 2020-01-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200130_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estandar',
            name='estandar_mayor',
            field=models.CharField(max_length=500),
        ),
    ]
