# Generated by Django 2.2 on 2020-01-31 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200130_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=200)),
                ('grado', models.CharField(max_length=200)),
                ('dba_mayor', models.CharField(max_length=500)),
                ('dba_menor', models.CharField(max_length=500)),
                ('fecha_sys', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
