# Generated by Django 2.2 on 2020-01-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dba',
            name='grado',
            field=models.IntegerField(),
        ),
    ]
