# Generated by Django 2.2 on 2020-01-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semana',
        ),
    ]
