# Generated by Django 2.2 on 2020-01-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='titulo',
            field=models.CharField(max_length=210),
        ),
    ]
