# Generated by Django 2.2 on 2020-01-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20200119_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
