# Generated by Django 2.2 on 2020-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_accion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='semana',
            name='periodo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='semana',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
