# Generated by Django 2.2 on 2020-01-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_accion', '0002_auto_20200119_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semana',
        ),
    ]
